apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-interview-monster
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      k8s-app: it-interview-monster
  template:
    metadata:
      labels:
        k8s-app: it-interview-monster
    spec:
      containers:
        - name: it-interview-monster
          image: ghcr.io/martynov-alex/it-interview-monster-backend:v0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 128Mi
