apiVersion: v1
kind: Service
metadata:
  name: itinterviewmonster
  namespace: default
spec:
  selector:
    k8s-app: itinterviewmonster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080