name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      ENV_VARIABLES:
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      ENV_SECRETS:
        required: true

env:
  SOURCE_FOLDER: backend
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/it-interview-monster-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout it-interview-monster-backend repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_FOLDER }}
          ref: ${{ inputs.TAG }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and prepare .env file
        run: |
          echo "APP_NAME=it-interview-monster" > ${{ env.SOURCE_FOLDER }}/.env
          echo "APP_VERSION=${{ inputs.TAG }}" >> ${{ env.SOURCE_FOLDER }}/.env
          echo "${{ inputs.ENV_VARIABLES }}" >> ${{ env.SOURCE_FOLDER }}/.env
          echo "${{ secrets.ENV_SECRETS }}" >> ${{ env.SOURCE_FOLDER }}/.env

      - name: Load env variables
        uses: falti/dotenv-action@v1
        with:
          path: ./${{ env.SOURCE_FOLDER }}/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.TAG }}
          push: true
          context: ${{ env.SOURCE_FOLDER }}

  migrate:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
        POSTGRES_USER: ''
        POSTGRES_PASSWORD: ''
        POSTGRES_HOST: ''
        POSTGRES_PORT: ''
        POSTGRES_DB_NAME: ''
        MIGRATE_PATH: migration/postgres
    steps:
      - name: Load env variables
        uses: falti/dotenv-action@v1
        with:
          path: ./${{ env.SOURCE_FOLDER }}/.env

      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
            path: ./${{ env.SOURCE_FOLDER }}/${{ env.MIGRATE_PATH }}
            database: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB_NAME }}
            command: up

  update-deployment-file:
    needs: migrate
    runs-on: ubuntu-latest
    env:
        DEPLOYMENT_FOLDER: deploy
        DEPLOYMENT_FILE: 1-deployment.yaml
    steps:
      - name: Checkout deploy repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/it-interview-monster-deploy
          path: ${{ env.DEPLOYMENT_FOLDER }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update deployment file, commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cd ${{ env.DEPLOYMENT_FOLDER }}/deployment/k8s-manifests
          sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${{ inputs.TAG }}|" ${{ env.DEPLOYMENT_FILE }}
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update deployment image version to ${{ inputs.TAG }}"
          git push
